services:
  - type: web
    name: immigration-lawyer-frontend
    runtime: node
    plan: free
    region: oregon
    branch: main
    rootDir: ./
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://immigration-lawyer-rag-backend.onrender.com
      - key: NODE_ENV
        value: production 